apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: yudao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8848
              name: http
            - containerPort: 9848
              name: grpc
            - containerPort: 9849
              name: grpc-tls
          env:
            - name: MODE
              value: "standalone"
            - name: JVM_XMS
              value: "512m"
            - name: JVM_XMX
              value: "512m"
            - name: JVM_XMN
              value: "256m"
            - name: NACOS_AUTH_ENABLE
              value: "false"
          readinessProbe:
            httpGet:
              path: /nacos/actuator/health
              port: 8848
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /nacos/actuator/health
              port: 8848
            initialDelaySeconds: 60
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: yudao
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
    - name: http
      port: 8848
      targetPort: 8848
      nodePort: 30848
    - name: grpc
      port: 9848
      targetPort: 9848
      nodePort: 30849
    - name: grpc-tls
      port: 9849
      targetPort: 9849
      nodePort: 30850
