apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: yudao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8848
              name: http
            - containerPort: 9848
              name: grpc
            - containerPort: 9849
              name: grpc-tls
          env:
            - name: MODE
              value: "standalone"
            - name: JVM_XMS
              value: "512m"
            - name: JVM_XMX
              value: "512m"
            - name: JVM_XMN
              value: "256m"
            # ✅ 开启 Nacos 登录鉴权
            - name: NACOS_AUTH_ENABLE
              value: "true"
            # ✅ 鉴权系统类型（2.x 必须）
            - name: NACOS_AUTH_SYSTEM_TYPE
              value: nacos
            # ✅ 身份校验（防止未授权访问）
            - name: NACOS_AUTH_IDENTITY_KEY
              value: nacos
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: nacos

---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: yudao
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
    - name: http
      port: 8848
      targetPort: 8848
    - name: grpc
      port: 9848
      targetPort: 9848
    - name: grpc-tls
      port: 9849
      targetPort: 9849
